source/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import CommentViewSet, LikeView, DislikeView

router = routers.DefaultRouter()
router.register(r'comments', CommentViewSet)



app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('like/<int:pk>/', LikeView.as_view(), name='like_image'),
    path('dislike/<int:pk>/', DislikeView.as_view(), name='dislike_image')
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/', include('api.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from webapp.views import IndexView, ImageView, ImageCreateView, ImageEditView, ImageDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('image/<int:pk>', ImageView.as_view(), name='image_detail'),
    path('image/create/',ImageCreateView.as_view(), name='image_create'),
    path('image/<int:pk>/edit/', ImageEditView.as_view(), name='image_edit'),
    path('image/delete/<int:pk>/', ImageDeleteView.as_view(), name='image_delete'),

    path('webapp/login/', LoginView.as_view(), name='login'),
    path('webapp/logout/', LogoutView.as_view(), name='logout'),

]

source/api/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Image(models.Model):
    photo = models.ImageField(upload_to='user_photo', verbose_name='Фотография')
    note = models.CharField(max_length=100, verbose_name='Подпись')
    like = models.IntegerField(default=0, verbose_name='Лайк')
    create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    author = models.ForeignKey(User, related_name='author_image', on_delete=models.CASCADE, default=None, verbose_name='Автор фото')

    def __str__(self):
        return self.note

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'


class Comment(models.Model):
    text = models.TextField(max_length=3000, verbose_name='Комментарий')
    photo = models.ForeignKey('webapp.Image', related_name='comments', on_delete=models.CASCADE, verbose_name='Фотография')
    author_comment = models.ForeignKey(User, related_name='author_comment', on_delete=models.CASCADE, default=None, verbose_name='Автор комментария')
    create_comment = models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Like(models.Model):
    author = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Пользователь')
    photo = models.ForeignKey('webapp.Image', related_name='liks', on_delete=models.CASCADE, verbose_name='Фото')

    def __str__(self):
        return f'{self.author.username} | {self.photo.note}'

    class Meta:
        unique_together = ('photo', 'author')

source/webapp/forms.py
from django import forms
from webapp.models import Image


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ['create_at', 'author']

source/api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet
from api.serializers import CommentSerializer

from webapp.models import Comment, Like, Image
from rest_framework.permissions import BasePermission

class IsAuthorPermission(BasePermission):            #Наследуется от BasePermission базовый класс для всех разрешений
                                                     #Разрешение для удаления файла для автора или пользователя с правом 'delete'

    # def has_permission(self, request, view):                 #только для комментария можно использовать
    #     if view.action == 'destroy':
    #         comment = Comment.objects.get(pk=view.kwargs.get('pk'))
    #         return comment.author_comment == request.user or request.user.has_perm('webapp.delete_comment')
    #     return super().has_permission(request, view)

    def has_object_permission(self, request, view, obj):                  #это вариант лучше
        if request.method in('DELETE', 'PUT', 'PATCH'):
            return obj.author_comment == request.user or request.user.has_perm('webapp.delete_comment')
        return True






class CommentViewSet(ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_permissions(self):
        if self.request.method == 'DELETE':
            return [IsAuthorPermission(), ]             #можно удалять только автору или пользвоателю с правом для удаления
        else:
            return super().get_permissions()


class LikeView(APIView):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        try:
            photo = Image.objects.get(pk=pk)
        except Image.DoesNotExist:
            return Response({'error:' 'Фото не найдено'}, status=404)
        try:
            Like.objects.get(photo=photo, author=request.user)                 #гарантировано будет юзер
            return Response({'error': 'Вы уже поставили лайк на это фото'}, status=400)
        except Like.DoesNotExist:
            Like.objects.create(photo=photo, author=request.user)          #если лайка не было , создаем лайк
            photo.like += 1
            photo.save()
            return Response({'id': photo.pk, 'like': photo.like})


class DislikeView(APIView):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        try:
            photo = Image.objects.get(pk=pk)
        except Image.DoesNotExist:
            return Response({'error:' 'Фото не найдено'}, status=404)
        try:
            Like.objects.get(photo=photo, author=request.user).delete()                 #если лайк был поставлпен, меняем на dislike
            photo.like -= 1
            photo.save()
            return Response({'id': photo.pk, 'like': photo.like})
        except Like.DoesNotExist:
            return Response({'error': 'Вы еще не ставили лайк на это фото'}, status=400)

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import request
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PhotoForm
from webapp.models import Image, Like
from django.views.decorators.csrf import ensure_csrf_cookie
from django.utils.decorators import method_decorator

@method_decorator(ensure_csrf_cookie, name='dispatch')               # при запросах чтобы токен приходил целиком
class IndexView(ListView):
    model = Image
    template_name = 'index.html'
    context_object_name = 'images_list'
    ordering = ['-create']

@method_decorator(ensure_csrf_cookie, name='dispatch')              # при запросах страниц токен должен приходить целиком
class ImageView(DetailView):
    model = Image
    template_name = 'detail.html'
    context_object_name = 'image'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            try:
                Like.objects.get(author= self.request.user, photo = self.object)  #self.object- текущий объект
                context['liked']=True
            except Like.DoesNotExist:
                context['liked'] = False
        return context


class ImageCreateView(LoginRequiredMixin, CreateView):
    model = Image
    template_name = 'create.html'
    form_class = PhotoForm

    def form_valid(self, form):
        self.object = self.model.objects.create(author=self.request.user, **form.cleaned_data)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:image_detail', kwargs={'pk': self.object.pk})


class ImageEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'edit.html'
    model = Image
    form_class = PhotoForm
    context_object_name = 'image'
    permission_required = 'webapp.change_image'

    def get_success_url(self):
        return reverse('webapp:image_detail', kwargs={'pk': self.object.pk})


class ImageDeleteView(PermissionRequiredMixin, DeleteView):
    model = Image
    template_name = 'delete.html'
    context_object_name = 'image'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_image'

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Моя галерея{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand font-weight-bold" href="">Моя галерея</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-3">
      <li class="nav-item ml-3 mr-3">
        <a class="nav-link font-weight-bolder" href="{% url 'webapp:index' %}">Главная</a>
      </li>
    {% if request.user.is_authenticated %}
      <li class="nav-item ml-3 mr-3">
        <a class="nav-link font-weight-bolder" href="{% url 'webapp:image_create'%}">Добавить фото</a>
      </li>
    {%  endif %}
    {% block menu %} {% endblock %}
        {% if request.user.is_authenticated %}
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger">Hello, {{ request.user }}!</a></li>
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'webapp:logout' %}">Выход</a></li>
        {% else %}
            <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-danger" href="{% url 'webapp:login' %}">Вход</a></li>
        {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
 {% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/exam.js' %}"></script>

{% endblock %}
</body>
</html>

source/webapp/templates/create.html
{% extends 'base.html' %}

{% block title %}Добавить фото{% endblock %}

{% block content %}
    <h1>Добавить фото</h1>
    <form method="POST" action="{% url "webapp:image_create"%}" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Создать' %}
    </form>
{% endblock %}

source/webapp/templates/delete.html
{% extends "base.html" %}
{% block title %}Удалить фото{% endblock %}

{% block content %}
    <h1 class="question text-center">Вы действительно хотите удалить фото?
        <br>
        <b>{{ image.note}}</b>?</h1>
    <form method="POST" action="{% url "webapp:image_delete" image.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Да, удалить!" class="btn btn-outline-dark"></p>
        <p><a href="{% url 'webapp:index' %}" class="btn btn-outline-dark">Нет. выйти!</a></p>
    </form>
{% endblock %}

source/webapp/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Просмотр фото{% endblock %}
{% block menu %}
    {% if perms.webapp.change_image %}
        <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-info" href="{% url 'webapp:image_edit' image.pk%}">Редактировать</a></li>
    {% endif %}
    {% if perms.webapp.delete_image %}
        <li class="nav-item ml-5 mr-3"><a class="nav-link font-weight-bolder text-info" href="{% url 'webapp:image_delete' image.pk %}">Удалить</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1> Мое фото</h1>
        <div class="row">
            <div class="col col-12 col-sm-10 col-md-8 col-lg-6 m-auto">
                <img src="{{ image.photo.url }}" class="card-img-top" alt="{{ image.note }}">
        <p class="card-text font-weight-bold">{{ image.note }}</p>
        <p>Автор фото: <b>{{image.author}}</b></p>

        <p><b>Дата создания: </b>{{ image.create| date:'d.m.Y H:i:s'}}</p>
            <p>Количество лайков: <span id="likes-display-{{ image.pk }}">{{image.like}}</span></p>
            {% if request.user.is_authenticated %}
            <p><a href=""><i class="like-btn fa fa-thumbs-up ml-3 display-4 {% if liked %} d-none {% endif %}" id="like-btn-{{ image.pk }}" data-id="{{ image.pk }}"></i></a>
                <a href=""><i class="dislike-btn fa fa-thumbs-down ml-5 display-4 {% if not liked %} d-none{% endif %}" id="dislike-btn-{{ image.pk }}" data-id="{{ image.pk }}"></i></a></p>
            {% endif %}
                <hr>
                <h3><b>Комментарии к фотографии:</b></h3>
    <div class="comment-list">
        {% for comment in image.comments.all %}
            <div class="comment">
            <div class="pre text-danger">{{ comment.text }}</div>
                <p class="mt-4">Комментарий от: {{ comment.author_comment }} ( {{ comment.create_comment|date:'d.m.Y H:i:s' }} )</p>
                <hr>
            {% if comment.author_comment == request.user%}
                <p class="review-links">
                    {% if perms.webapp.change_comment %}
                        <a href="#" class="btn btn-primary">Редактировать</a>
                    {% endif %}
                    {% if request.user == comment.author or perms.webapp.delete_comment%}
                        <a href="#" class="btn btn-primary" id="delete_comment" onclick="deleteComment({{ comment.pk }})">Удалить</a>
                    {% endif %}
                </p>
            {% endif %}

            </div>
     {% empty %}
            <p>Комментариев еще нет.</p>
        {% endfor %}

    {% if request.user.is_authenticated %}
    <h5><b>Добавить новый комментарий:</b></h5>
        <form action="#" method="POST" id="add_comment">
    {% csrf_token %}
        <input type="hidden" id="image" value="{{ image.pk }}" style="width: 60%;">
        <div class="photo">
            <input type="text" id="image_comment" style="width: 60%;">
        </div>
        <button type="submit" class="btn btn-primary mt-3" id="add_link">Добавить</button>
    </form>
    {% endif %}
            <hr>
            </div>
    </div>
    </div>
{% endblock %}

source/webapp/templates/edit.html
{% extends 'base.html' %}

{% block title %}Редактировать фото{% endblock %}

{% block content %}
    <h1>Редактировать фото</h1>
    <form method="POST" action="{% url "webapp:image_edit" image.pk%}" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Редактировать' %}
    </form>
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Галерея</h1>
    <hr/>
    {%  for image in images_list %}
 <div class="card text-center m-5" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title">Мои фото!</h5>
        <img src="{{ image.photo.url }}" class="card-img-top" alt="{{ image.note }}">
        <p class="card-text font-weight-bold">{{ image.note }}</p>
        <p>Автор фото: <b>{{image.author}}</b></p>
{#        <p>Количество лайков: <b>{{image.like}}</b></p>#}
        <p><b>Дата создания: </b>{{ image.create| date:'d.m.Y H:i:s'}}</p>
      <p>Количество лайков: <span id="likes-display-{{ image.pk }}">{{image.like}}</span></p>
            {%  if requset.user.is_authenticated %}
            <p><a href=""><i class="like-btn fa fa-thumbs-up ml-3 display-4" id="like-btn-{{ image.pk }}" data-id="{{ image.pk }}"></i></a>
                <a href=""><i class="dislike-btn fa fa-thumbs-down ml-5 display-4" id="dislike-btn-{{ image.pk }}" data-id="{{ image.pk }}"></i></a></p>
            {% endif %}
      <a href="{% url 'webapp:image_detail' image.pk %}" class="btn btn-outline-dark ml-3">Подробнее</a>
  </div>
</div>
    {% endfor %}

{% endblock %}

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p class="ml-3 mb-0"><label for="{{ field.id_for_label }}">{{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label></p>
    <p class="col-7 ml-0 d-inline-block">{{ field|add_class:'form-control' }}</p>
    {% for error in field.errors %}
        <small class="text-danger ml-3">{{ error }}</small>
    {% endfor %}
{% endfor %}

<p class="ml-3">
    <input type="submit" value="{{ button_text }}" class="btn btn-outline-dark">
</p>